spring.datasource.url=jdbc:postgresql://postgresql-17:5432/postgresql-jw-visit
spring.datasource.username=postgresql-jw-visit
spring.datasource.password=pwd_3kw7sR
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ls-visit}
#spring.datasource.username=${DATABASE_USERNAME:postgres}
#spring.datasource.password=${DATABASE_PASSWORD:admin}

# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.show-sql=false

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}

app.jwt.secret=${JWT_SECRET:MinhaChaveJWTSuperSeguraComMaisDe32Caracteres123MinhaChaveJWTSuperSeguraComMaisDe32Caracteres123}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
spring.jackson.property-naming-strategy=SNAKE_CASE

# Usuário administrador criado/atualizado automaticamente na inicialização
app.bootstrap.admin-email=${ADMIN_EMAIL:admin@lsmapas.com}
app.bootstrap.admin-name=${ADMIN_NAME:Administrador}
app.bootstrap.admin-password=${ADMIN_PASSWORD:Admin@123}
app.upload-dir=${UPLOAD_DIR:uploads}
